version: "3"

services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql-server
    volumes:
      #- ./mysql_data:/var/lib/mysql
      - ./hive/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
          - seccomp:unconfined
  hive-server:
    image: hadoop-hive:hadoop2.10.2_java8
#    env_file:
#      - hive/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "mysql:3306"
    ports:
      - "9999:9999"
      - "10000:10000"
      - "10002:10002"
volumes:
  namenode:
  datanode:

networks:
  default:
    external:
      name: docker-hadoop-master_default
