version: '2'
services:
 flink-master:
   image: flink-master:1.16.3_scala_2.12
   hostname: flink-master
   container_name: flink-master
   ports:
     - "8080:8080"
     - "8081:8081"

 flink-worker:
   image: flink-worker:1.16.3_scala_2.12
   hostname: flink-worker
   container_name: flink-worker
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
#     - FLINK_NUM_TASK_SLOTS=2
   depends_on:
      - flink-master


networks:
  default:
    external:
      name: docker-hadoop-master_default
