version: "3"

services:
  namenode:
    image: hadoop-namenode:hadoop2.10.2_java8
    container_name: namenode
    restart: always
    ports:
      - 50070:50070
      - 8020:8020
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: hadoop-datanode:hadoop2.10.2_java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
  resourcemanager:
    image: hadoop-resourcemanager:hadoop2.10.2_java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
      TZ: "Asia/Shanghai"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: hadoop-nodemanager:hadoop2.10.2_java8
    container_name: nodemanager
    restart: always
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
      TZ: "Asia/Shanghai"
    env_file:
      - ./hadoop.env

  historyserver:
    image: hadoop-historyserver:hadoop2.10.2_java8
    container_name: historyserver
    restart: always
    ports:
      - 19888:19888
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
      TZ: "Asia/Shanghai"
    volumes:
      - /usr/local/docker/hadoop/hadoop1/yarn/timeline:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  wordcount:
    image: hadoop-wordcount:hadoop2.10.2_java8
    container_name: wordcount
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088 historyserver:19888"



# docker network create mynetwork
networks:
  default:
    external:
      name: docker-hadoop-master_default
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
