version: "3"

services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql-server
    volumes:
      #- ./mysql_data:/var/lib/mysql
      - ./hive/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hive_meta
    security_opt:
      - seccomp:unconfined
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
  hive-server:
    image: hadoop-hive:hadoop3.3.6_java8
    env_file:
      - hive/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "172.17.0.1:3306 namenode:9000"
    depends_on:
      - mysql
    ports:
      - "9083:9083"
      - "10000:10000"
volumes:
  namenode:
  datanode:
networks:
  default:
    external:
      name: docker-hadoop-master_default
