FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openssh-server wget net-tools curl netcat libsnappy-dev default-mysql-client && \
    rm -rf /var/lib/apt/lists/* && \
    wget https://repo.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.tar.gz --no-check-certificate -O /tmp/jdk-8u202-linux-x64.tar.gz && \
    tar -xzvf /tmp/jdk-8u202-linux-x64.tar.gz -C /tmp && \
    mv /tmp/jdk1.8.0_202 /usr/local/jdk1.8 && \
    rm /tmp/jdk*

ENV DORIS_VERSION=2.0.2 \
    DORIS_URL=https://apache-doris-releases.oss-accelerate.aliyuncs.com/apache-doris-$DORIS_VERSION-bin-x64.tar.gz

RUN wget "$DORIS_URL" --no-check-certificate -O /tmp/doris.tar.gz && \
    tar -xvf /tmp/doris.tar.gz -C /opt/ && \
    rm /tmp/doris.tar.gz* && \
    apt-get update && \
    apt-get install -y default-mysql-client && \
    apt-get clean && \
    mkdir /opt/apache-doris && \
    mv /opt/apache-doris-$DORIS_VERSION-bin-x64/fe /opt/apache-doris/fe && \
    rm -rf /opt/apache-doris-$DORIS_VERSION-bin-x64

COPY ./init_fe.sh /opt/apache-doris/fe/bin
RUN chmod 755 /opt/apache-doris/fe/bin/init_fe.sh

ENTRYPOINT ["/opt/apache-doris/fe/bin/init_fe.sh"]
